def uncharted(x):
  if x >= 2:
    print("Hello User")
  else:
    print("Goodbye User")

print("Daily Commit 1")
print("Daily Commit 2")
print("Daili Commit 3")
print("Daily Commit 4")
print("Daily Commit 5")
print("Daily Commit 6")
print("Daily Commit 7")
print("Daily Commit 8")
print("Daily Commit 9")
print("Daily Commit 10")
print("Daily Commit 11")
print("Daily Commit 12")
print("Daily Commit 13")
print("Daily Commit 14")
print("Daily Commit 15")
print("Half-Way")
print("Daily Commit 16")
print("Daily Commit 17")
print("Daily Commit 18")
print("Daily Commit 19")

uncharted(3)
uncharted(2)
uncharted(1)
uncharted(4)
uncharted(5)
