def uncharted(x):
  if x >= 2:
    print("Hello User")
  else:
    print("Goodbye User")

print("Daily Commit 1")
print("Daily Commit 2")
print("Daili Commit 3")
print("Daily Commit 4")
print("Daily Commit 5")
print("Daily Commit 6")
print("Daily Commit 7")
print("Daily Commit 8")
print("Daily Commit 9")
print("Daily Commit 10")
print("Daily Commit 11")
print("Daily Commit 12")
print("Daily Commit 13")
print("Daily Commit 14")
print("Daily Commit 15")
print("Half-Way")
print("Daily Commit 16")
print("Daily Commit 17")
print("Daily Commit 18")
print("Daily Commit 19")
print("Daily Commit 20")
print("Daily Commit 21")
print("Daily Commit 22")
print("Daily Commit 23")
print("Daily Commit 24")
print("Daily Commit 25")
print("Daily Commit 26")
print("Daily Commit 27")
print("Daily Commit 28")
print("Daily Commit 29")
print("Daily Commit 30")
print("New Goal is set")
print("Daily Commit 31")
print("Daily Commit 32")
print("Daily Commit 33")
print("Daily Commit 34")
print("Daily Commit 35")
print("daily Commit 36")
print("Daily Commit 37")
print("Daily Commit 38")
print("Daily Commit 39")

uncharted(3)
uncharted(2)
uncharted(1)
uncharted(4)
uncharted(5)
uncharted(6)
uncharted(1)
