def uncharted(x):
  if x >= 2:
    print("Hello User")
  else:
    print("Goodbye User")

print("Daily Commit 1")
print("Daily Commit 2")
print("Daili Commit 3")
print("Daily Commit 4")
print("Daily Commit 5")
print("Daily Commit 6")
print("Daily Commit 7")
print("Daily Commit 8")
print("Daily Commit 9")
print("Daily Commit 10")
print("Daily Commit 11")
print("Daily Commit 12")
print("Daily Commit 13")
print("Daily Commit 14")
print("Daily Commit 15")
print("Half-Way")
print("Daily Commit 16")
print("Daily Commit 17")
print("Daily Commit 18")
print("Daily Commit 19")
print("Daily Commit 20")
print("Daily Commit 21")
print("Daily Commit 22")
print("Daily Commit 23")
print("Daily Commit 24")
print("Daily Commit 25")
print("Daily Commit 26")
print("Daily Commit 27")
print("Daily Commit 28")
print("Daily Commit 29")
print("Daily Commit 30")
print("New Goal is set")
print("Daily Commit 31")
print("Daily Commit 32")
print("Daily Commit 33")
print("Daily Commit 34")
print("Daily Commit 35")
print("daily Commit 36")
print("Daily Commit 37")
print("Daily Commit 38")
print("Daily Commit 39")
print("Daily Commit 40")
print("Daily Commit 41")
print("Daily Commit 42")
print("Daily Commit 43")
print("Daily Commit 44")
print("Daily Commit 45")
print("Daily Commit 46")
print("Daily Commit 47")
print("Daily Commit 48")
print("Daily Commit 49")
print("Daily Commit 50")
print("Daily Commit 51")
print("Daily Commit 52")
print("Daily Commit 53")
print("Daily Commit 54")
print("Daily Commit 55")
print("Daily Commit 56")
print("Daily Commit 57")
print("Daily Commit 58")
print("Daily Commit 59")
print("Daily Commit 60")
print("Daily Commit 61")
print("Daily Commit 62")
print("Daily Commit 63")
print("Daily Commit 64")
print("Daily Commit 65")
print("Daily Commit 66")
print("Daily Commit 67")
print("Daily Commit 68")
print("Daily Commit 69")
print("Daily Commit 70")
print("Daily Commit 71")
print("Daily Commit 72")
print("Daily Commit 73")
print("Daily Commit 74")
print("Daily Commit 75")
print("Daily Commit 76")
print("Daily Commit 77")
print("Daily Commit 78")
print("Daily Commit 79")
print("Daily Commit 80")
print("Daily Commit 81")
print("Daily Commit 82")
print("Daily Commit 83")
print("Daily Commit 84")
print("Daily Commit 85")
print("Daily Commit 86")
print("Daily Commit 87")
print("Daily Commit 88")
print("Daily Commit 89")
print("Daily Commit 90")
print("Daily Commit 91")
print("Daily Commit 92")
print("Daily Commit 93")
print("Daily Commit 94")
print("Daily Commit 95")
print("Daily Commit 96")
print("Daily Commit 97")
print("Daily Commit 98")
print("Daily Commit 99")
print("Daily Commit 100")
print("!!!")
print("Daily Commit 101")
print("Daily Commit 102")
print("Daily Commit 103")
print("Daily Commit 104")
print("Daily Commit 105")
print("Daily Commit 106")
print("Daily Commit 107")
print("Daily Commit 108")
print("Daily Commit 109")
print("Daily Commit 110")
print("Daily Commit 111")
print("Daily Commit 112")
print("Daily Commit 113")
print("Daily Commit 114")



uncharted(3)
uncharted(2)
uncharted(1)
uncharted(4)
uncharted(5)
uncharted(6)
uncharted(1)
uncharted(6)
uncharted(12)
uncharted(6)
